version: "3.6"
services:
  pihole-template:
    container_name: "pihole-template"
    entrypoint:
      - "/s6-init"
    environment:
      - "UDP_PORT_53=53"
      - "TCP_PORT_443=443"
      - "ServerIPv6="
      - "ServerIP=10.0.0.6"
      - "WEBUIBOXEDLAYOUT=boxed"
      - "TCP_PORT_53=53"
      - "INTERFACE=br0"
      - "IPv6=False"
      - "DNS2=1.0.0.1"
      - "DNSMASQ_LISTENING=all"
      - "PIHOLE_DNS_=8.8.8.8;8.8.4.4"
      - "HOST_CONTAINERNAME=pihole-template"
      - "UDP_PORT_67=67"
      - "TCP_PORT_80=80"
      - "DNS1=1.1.1.1"
      - "PATH=/opt/pihole:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "phpver=php"
      - "PHP_ENV_CONFIG=/etc/lighttpd/conf-enabled/15-pihole-admin.conf"
      - "PHP_ERROR_LOG=/var/log/lighttpd/error-pihole.log"
      - "S6_KEEP_ENV=1"
      - "S6_BEHAVIOUR_IF_STAGE2_FAILS=2"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "FTLCONF_LOCAL_IPV4=0.0.0.0"
      - "VIRTUAL_HOST="
      - "FTL_CMD=no-daemon"
      - "DNSMASQ_USER=pihole"
    expose:
      - "53/tcp"
      - "53/udp"
      - "67/udp"
      - "80/tcp"
    hostname: "4c8cff056222"
    image: "pihole/pihole:latest"
    ipc: "private"
    labels:
      net.unraid.docker.icon: "https://i.imgur.com/OWkNcEn.png"
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "http://[IP]:[PORT:80]/admin"
      org.opencontainers.image.created: "2023-01-16T08:47:31.607Z"
      org.opencontainers.image.description: "Pi-hole in a docker container"
      org.opencontainers.image.licenses: ""
      org.opencontainers.image.revision: "45d5fa753a0dcd6f31687aeaa8f63f7a0ab7cd7c"
      org.opencontainers.image.source: "https://github.com/pi-hole/docker-pi-hole"
      org.opencontainers.image.title: "docker-pi-hole"
      org.opencontainers.image.url: "https://github.com/pi-hole/docker-pi-hole"
      org.opencontainers.image.version: "2023.01"
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "500m"
    networks:
      - "br0"
    restart: "unless-stopped"
    volumes:
      - "/DATA/AppData/pihole/dnsmasq.d:/etc/dnsmasq.d"
      - "/DATA/AppData/pihole/pihole:/etc/pihole"
