version: "3.6"
services:
  ombi:
    container_name: "ombi"
    entrypoint:
      - "/init"
    environment:
      - "HOST_CONTAINERNAME=ombi"
      - "PUID=1000"
      - "PGID=1000"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "HOME=/config"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "DEBIAN_FRONTEND=noninteractive"
    hostname: "5e16ed1d53b8"
    image: "linuxserver/ombi"
    ipc: "private"
    labels:
      build_version: "Linuxserver.io version:- v4.22.5-ls148 Build-date:- 2023-01-10T02:32:02-06:00"
      maintainer: "aptalca"
      net.unraid.docker.icon: "https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/ombi.png"
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "http://[IP]:[PORT:3579]/"
      org.opencontainers.image.authors: "linuxserver.io"
      org.opencontainers.image.created: "2023-01-10T02:32:02-06:00"
      org.opencontainers.image.description:
        "[Ombi](https://ombi.io) allows you to\
        \ host your own Plex Request and user management system.  If you are sharing\
        \ your Plex server with other users, allow them to request new content using\
        \ an easy to manage interface!  Manage all your requests for Movies and TV\
        \ with ease, leave notes for the user and get notification when a user requests\
        \ something.  Allow your users to post issues against their requests so you\
        \ know there is a problem with the audio etc.  Even automatically send them\
        \ weekly newsletters of new content that has been added to your Plex server!"
      org.opencontainers.image.documentation: "https://docs.linuxserver.io/images/docker-ombi"
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.ref.name: "f15fcb2edbd1ffbc8a9e78005a68140b00d2a9e8"
      org.opencontainers.image.revision: "f15fcb2edbd1ffbc8a9e78005a68140b00d2a9e8"
      org.opencontainers.image.source: "https://github.com/linuxserver/docker-ombi"
      org.opencontainers.image.title: "Ombi"
      org.opencontainers.image.url: "https://github.com/linuxserver/docker-ombi/packages"
      org.opencontainers.image.vendor: "linuxserver.io"
      org.opencontainers.image.version: "v4.22.5-ls148"
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "500m"
    networks:
      - "alphaproxy"
    ports:
      - "3579:3579/tcp"
    volumes:
      - "/DATA/AppData/ombi:/config"
    working_dir: "/"

