version: "3.6"
services:
  redis:
    command:
      - "/opt/bitnami/scripts/redis/run.sh"
    container_name: "redis"
    entrypoint:
      - "/opt/bitnami/scripts/redis/entrypoint.sh"
    environment:
      - "HOST_CONTAINERNAME=redis"
      - "ALLOW_EMPTY_PASSWORD=no"
      - "PATH=/opt/bitnami/common/bin:/opt/bitnami/redis/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "HOME=/"
      - "OS_ARCH=amd64"
      - "OS_FLAVOUR=debian-11"
      - "OS_NAME=linux"
      - "APP_VERSION=7.0.8"
      - "BITNAMI_APP_NAME=redis"
    hostname: "4c0046597c1d"
    image: "bitnami/redis:latest"
    ipc: "private"
    labels:
      net.unraid.docker.icon: "https://raw.githubusercontent.com/A75G/docker-templates/master/templates/icons/redis.png"
      net.unraid.docker.managed: "dockerman"
      org.opencontainers.image.authors: "https://bitnami.com/contact"
      org.opencontainers.image.description: "Application packaged by Bitnami"
      org.opencontainers.image.licenses: "Apache-2.0"
      org.opencontainers.image.ref.name: "7.0.8-debian-11-r1"
      org.opencontainers.image.source: "https://github.com/bitnami/containers/tree/main/bitnami/redis"
      org.opencontainers.image.title: "redis"
      org.opencontainers.image.vendor: "VMware, Inc."
      org.opencontainers.image.version: "7.0.8"
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "500m"
    networks:
      - "alphaproxy"
    ports:
      - "6379:6379/tcp"
    restart: "unless-stopped"
    user: "1001"