version: "3.6"
services:
  scrutiny:
    command:
      - "/init"
    container_name: "scrutiny"
    environment:
      - "HOST_CONTAINERNAME=scrutiny"
      - "PATH=/opt/scrutiny/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "INFLUXD_CONFIG_PATH=/opt/scrutiny/influxdb"
    hostname: "7c28a36610b5"
    image: "ghcr.io/analogj/scrutiny:master-omnibus"
    ipc: "private"
    labels:
      net.unraid.docker.icon: "https://raw.githubusercontent.com/selfhosters/unRAID-CA-templates/master/templates/img/scrutiny.png"
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "http://[IP]:[PORT:8083]"
      org.opencontainers.image.created: "2023-01-12T02:07:59.961Z"
      org.opencontainers.image.description:
        "Hard Drive S.M.A.R.T Monitoring, Historical\
        \ Trends & Real World Failure Thresholds"
      org.opencontainers.image.licenses: "MIT"
      org.opencontainers.image.revision: "d49497da805327dec2a6dc33010676b260188e5a"
      org.opencontainers.image.source: "https://github.com/AnalogJ/scrutiny"
      org.opencontainers.image.title: "scrutiny"
      org.opencontainers.image.url: "https://github.com/AnalogJ/scrutiny"
      org.opencontainers.image.version: "master-omnibus"
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "500m"
    networks:
      - "alphaproxy"
    ports:
      - "8083:8080/tcp"
    privileged: true
    security_opt:
      - "label=disable"
    volumes:
      - "/DATA/AppData/scrutiny:/opt/scrutiny/influxdb"
      - "/run/udev:/run/udev:ro"
      - "/dev/disk:/dev/disk:ro"
      - "/DATA/AppData/scrutiny:/opt/scrutiny/config"
    working_dir: "/opt/scrutiny"

