version: "3.6"
services:
  Tailscale:
    container_name: "Tailscale"
    entrypoint:
      - "/app/docker-entrypoint.sh"
    environment:
      - "UP_FLAGS=--advertise-exit-node"
      - "HOST_CONTAINERNAME=Tailscale"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    hostname: "unraid"
    image: "deasmi/unraid-tailscale:latest"
    ipc: "private"
    labels:
      net.unraid.docker.icon: "https://raw.githubusercontent.com/deasmi/unraid-tailscale/master/logo.png"
      net.unraid.docker.managed: "dockerman"
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "500m"
    network_mode: "host"
    privileged: true
    security_opt:
      - "label=disable"
    volumes:
      - "/DATA/AppData/tailscale:/state"
    working_dir: "/app"
