version: "3.6"
services:
  Plex-Meta-Manager:
    container_name: "Plex-Meta-Manager"
    entrypoint:
      - "/tini"
      - "-s"
      - "python3"
      - "plex_meta_manager.py"
      - "--"
    environment:
      - "HOST_CONTAINERNAME=Plex-Meta-Manager"
      - "PMM_TIME=6:00"
      - "PMM_DIVIDER=="
      - "PMM_WIDTH=200"
      - "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "GPG_KEY=${PLEX_META_MANAGER_GPG_KEY}"
      - "PYTHON_VERSION=3.11.1"
      - "PYTHON_PIP_VERSION=22.3.1"
      - "PYTHON_SETUPTOOLS_VERSION=65.5.1"
      - "PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/66030fa03382b4914d4c4d0896961a0bdeeeb274/public/get-pip.py"
      - "PYTHON_GET_PIP_SHA256=1e501cf004eac1b7eb1f97266d28f995ae835d30250bec7f8850562703067dc6"
      - "TINI_VERSION=v0.19.0"
      - "PMM_DOCKER=True"
    hostname: "ccb81b85b634"
    image: "meisnate12/plex-meta-manager"
    ipc: "private"
    labels:
      net.unraid.docker.icon: "https://metamanager.wiki/en/latest/_static/pmm.png"
      net.unraid.docker.managed: "dockerman"
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "500m"
    networks:
      - "alphaproxy"
    volumes:
      - "/DATA/AppData/Plex-Meta-Manager:/config"

