version: "3.6"
services:
  PhotoPrism:
    command:
      - "/opt/photoprism/bin/photoprism"
      - "start"
    container_name: "PhotoPrism"
    entrypoint:
      - "/scripts/entrypoint.sh"
    environment:
      - "PHOTOPRISM_AUTO_IMPORT=180"
      - "PHOTOPRISM_JPEG_QUALITY=90"
      - "PHOTOPRISM_STORAGE_PATH=/photoprism/storage"
      - "PHOTOPRISM_SITE_TITLE=PhotoPrism"
      - "PHOTOPRISM_SITE_DESCRIPTION="
      - "PHOTOPRISM_SITE_AUTHOR="
      - "PHOTOPRISM_THUMB_FILTER=lanczos"
      - "PHOTOPRISM_EXPERIMENTAL=false"
      - "PHOTOPRISM_UID=1000"
      - "PHOTOPRISM_SITE_CAPTION=Browse Your Life"
      - "PHOTOPRISM_JPEG_SIZE=7680"
      - "PHOTOPRISM_THUMB_UNCACHED=false"
      - "PHOTOPRISM_THUMB_SIZE=2048"
      - "PHOTOPRISM_THUMB_SIZE_UNCACHED=7680"
      - "PHOTOPRISM_DATABASE_DSN=photoprism:ant*ctv6pkv5GDK-akt@tcp(mariadb:3306)/photoprism?parseTime=true"
      - "PHOTOPRISM_AUTO_INDEX=180"
      - "PHOTOPRISM_UID=1000"
      - "PHOTOPRISM_UPLOAD_NSFW=true"
      - "PHOTOPRISM_DATABASE_DRIVER=mysql"
      - "PHOTOPRISM_DARKTABLE_PRESETS=false"
      - "HOST_CONTAINERNAME=PhotoPrism"
      - "PHOTOPRISM_DETECT_NSFW=false"
      - "PHOTOPRISM_SETTINGS_HIDDEN=false"
      - "PATH=/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/scripts:/opt/photoprism/bin"
      - "PHOTOPRISM_ARCH=amd64"
      - "DOCKER_TAG=221118-jammy"
      - "DOCKER_ENV=prod"
      - "PS1=\\u@:\\w$ "
      - "LD_LIBRARY_PATH=/usr/local/lib:/usr/lib"
      - "TMPDIR=/tmp"
      - "DEBIAN_FRONTEND=noninteractive"
      - "TF_CPP_MIN_LOG_LEVEL=2"
      - "PROG=photoprism"
      - "PHOTOPRISM_ASSETS_PATH=/opt/photoprism/assets"
      - "PHOTOPRISM_IMPORT_PATH=/photoprism/import"
      - "PHOTOPRISM_ORIGINALS_PATH=/photoprism/originals"
      - "PHOTOPRISM_BACKUP_PATH=/photoprism/storage/backups"
      - "PHOTOPRISM_LOG_FILENAME=/photoprism/storage/photoprism.log"
      - "PHOTOPRISM_PID_FILENAME=/photoprism/storage/photoprism.pid"
      - "PHOTOPRISM_DEBUG=false"
      - "PHOTOPRISM_PUBLIC=false"
      - "PHOTOPRISM_READONLY=false"
      - "PHOTOPRISM_SITE_URL=http://photoprism.me:2342/"
      - "PHOTOPRISM_HTTP_HOST=0.0.0.0"
      - "PHOTOPRISM_HTTP_PORT=2342"
      - "PHOTOPRISM_DATABASE_SERVER="
      - "PHOTOPRISM_DATABASE_NAME=photoprism"
      - "PHOTOPRISM_DATABASE_USER=photoprism"
      - "PHOTOPRISM_DATABASE_PASSWORD="
      - "PHOTOPRISM_DISABLE_CHOWN=false"
      - "PHOTOPRISM_DISABLE_WEBDAV=false"
      - "PHOTOPRISM_DISABLE_SETTINGS=false"
      - "PHOTOPRISM_DISABLE_BACKUPS=false"
      - "PHOTOPRISM_DISABLE_EXIFTOOL=false"
      - "PHOTOPRISM_DISABLE_PLACES=false"
      - "PHOTOPRISM_DISABLE_TENSORFLOW=false"
      - "PHOTOPRISM_DISABLE_FACES=false"
      - "PHOTOPRISM_DISABLE_CLASSIFICATION=false"
      - "PHOTOPRISM_RAW_PRESETS=false"
      - "PHOTOPRISM_WORKERS=0"
      - "PHOTOPRISM_WAKEUP_INTERVAL=900"
    hostname: "ab5d1237ef13"
    image: "photoprism/photoprism"
    ipc: "private"
    labels:
      net.unraid.docker.icon: "https://raw.githubusercontent.com/ich777/docker-templates/master/ich777/images/photoprism.png"
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "http://[IP]:[PORT:2342]/"
      org.opencontainers.image.authors: "Michael Mayer <hello@photoprism.app>"
      org.opencontainers.image.description: "Ubuntu 22.04 LTS (Jammy Jellyfish)"
      org.opencontainers.image.documentation: "https://docs.photoprism.app/getting-started/"
      org.opencontainers.image.source: "https://github.com/photoprism/photoprism"
      org.opencontainers.image.title:
        "PhotoPrism® Community Edition (Ubuntu 22.04\
        \ LTS)"
      org.opencontainers.image.url: "https://hub.docker.com/repository/docker/photoprism/photoprism"
      org.opencontainers.image.vendor: "PhotoPrism UG"
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "500m"
    networks:
      - "alphaproxy"
    ports:
      - "2342:2342/tcp"
    restart: "unless-stopped"
    volumes:
      - "/DATA/backup/Photos:/backupphotos"
      - "/DATA/media/familyphotos:/photoprism/import"
      - "/DATA/media/photoprism:/photoprism/originals"
      - "/DATA/AppData/photoprism:/photoprism/storage"
    working_dir: "/photoprism"
